[package]
name = "r-sensor"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.33.1"                      # Para informações gerais do sistema
nvml-wrapper = "0.10"                 # Para monitoramento de GPUs Nvidia
async-std = {version = "1.12.0", features = ["attributes"]}
